backend:
  name: git-gateway
  branch: main
  identity_url: https://shimmering-granita-0d626d.netlify.app/.netlify/identity
  gateway_url: https://shimmering-granita-0d626d.netlify.app/.netlify/git

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/intro.json"
        label: "Intro"
        name: "intro"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Paragraphe", name: "lead", widget: "text" }


