backend:
  name: git-gateway
  branch: main

media_folder: "Images"
public_folder: "/Images"

site_url: "https://shimmering-granita-0d626d.netlify.app"
logo_url: "/logo-101.png"
publish_mode: editorial_workflow

collections:
  - label: "Contenu de la page"
    name: "home"
    files:
      - label: "Page d'accueil"
        name: "homejson"
        file: "content/home.json"
        fields:
          - { label: "Header (haut de page)", name: "header", widget: "markdown" }
          - { label: "Héro", name: "hero", widget: "markdown" }
          - { label: "Calendrier", name: "calendrier", widget: "markdown" }
          - { label: "Schéma", name: "schema", widget: "markdown" }
          - { label: "Rôle EC", name: "role_ec", widget: "markdown" }
          - { label: "Diagnostic (intro)", name: "diagnostic_intro", widget: "markdown" }
          - { label: "FAQ", name: "faq", widget: "markdown" }
          - { label: "Glossaire", name: "glossaire", widget: "markdown" }
          - { label: "Contact", name: "contact", widget: "markdown" }
          - { label: "Pied de page", name: "footer", widget: "markdown" }
